name: pokedex_bloc
description: Pokedex Bloc

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  http: ^0.13.1
  cached_network_image: ^3.0.0
  sliding_up_panel: ^1.0.2
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/pokeball.png
    - assets/images/types/Bug.png
    - assets/images/types/Dark.png
    - assets/images/types/Dragon.png
    - assets/images/types/Electric.png
    - assets/images/types/Fairy.png
    - assets/images/types/Fight.png
    - assets/images/types/Fire.png
    - assets/images/types/Flying.png
    - assets/images/types/Ghost.png
    - assets/images/types/Grass.png
    - assets/images/types/Ground.png
    - assets/images/types/Ice.png
    - assets/images/types/Normal.png
    - assets/images/types/Poison.png
    - assets/images/types/Psychic.png
    - assets/images/types/Rock.png
    - assets/images/types/Steel.png
    - assets/images/types/Water.png